name: Test Kernel Manifest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Repo Tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+rx ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Clean Existing Directories
        run: |
          rm -rf kernel_platform

      - name: Initialize Repo
        run: |
          repo init -u https://github.com/wanwei1028/kernel_manifest.git -b main -m oneplus_13.xml
          repo sync -j$(nproc) --force-sync

      - name: Debug Directory Structure
        run: |
          echo "=== 根目录结构 ==="
          ls -l
          echo "=== kernel_platform/msm-kernel/ ==="
          ls -l kernel_platform/msm-kernel/

      - name: Validate Symbolic Links
        run: |
          cd kernel_platform
          [ -L WORKSPACE ] || { echo "❌ WORKSPACE link missing"; exit 1; }
          [ -L build_with_bazel.py ] || { echo "❌ build_with_bazel.py link missing"; exit 1; }
          [ "$(readlink WORKSPACE)" = "msm-kernel/bazel.WORKSPACE" ] || { echo "❌ WORKSPACE link target mismatch"; exit 1; }
          [ "$(readlink build_with_bazel.py)" = "msm-kernel/build_with_bazel.py" ] || { echo "❌ build_with_bazel.py link target mismatch"; exit 1; }
          echo "✅ All symbolic links are valid"
